### ISSUE TITLE
Limited scrolling on Andriod

### ISSUE THREAD

**Issue by josephrmartinez** [aiDotEngineer/network#1]
I'm using the Android version of the app. Having an issue with limited scroll in the schedule section.

Currently unable to scroll past 3:00 pm on Sunday, 6:55 pm on Monday, or 4:33 pm on Tuesday.

**Comment by sstur** [comment]
You're right. It's a known issue. Fix going out soon!

**Comment by sstur** [comment]
The fix for this went out yesterday morning. Let me know if any further issue. Thanks!
